---
engines:
  phpcodesniffer:
    enabled: true
    config:
      standard: "WordPress"
  duplication:
    enabled: true
    config:
      languages:
      - php
  fixme:
    enabled: true
  phpmd:
    enabled: true
    config:
      rulesets: "cleancode,codesize,design,naming,unusedcode"
ratings:
  paths:
    - "src/**.php"
    - "tests/**.spec.php"
exclude_paths:
  - "src/**/*"
  - "!src/**.php"
  - node_modules/
  - "**/vendor/**/*"
